config/routes.rb
SpeedupDashboard::Engine.routes.draw do

  root 'requests#index'

  resources :requests, only: [:create]

  resources :servers do
    resources :requests, only: [:index, :show]
    resources :actions
    resources :contexts
  end

  resources :contexts

end

app/models/speedup_dashboard/context.rb
module SpeedupDashboard
  class Context < ActiveRecord::Base
    belongs_to :request
    has_many :context_infos

    def self.average_info_count
      values = joins("LEFT OUTER JOIN #{ContextInfo.table_name} ON #{table_name}.id = #{ContextInfo.table_name}.context_id").
      group("#{table_name}.id").count(:context_id).values

      values.any? ? values.sum / values.size : 0
    end

  end
end

app/models/speedup_dashboard/context_info.rb
module SpeedupDashboard
  class ContextInfo < ActiveRecord::Base
    belongs_to :context, counter_cache: true

    serialize :data
  end
end

app/models/speedup_dashboard/request.rb
module SpeedupDashboard
  class Request < ActiveRecord::Base
    belongs_to :server
    has_many :contexts
    has_many :context_infos, through: :contexts

    scope :between, ->(from, to=Time.now) { where( time: from..to ) }

    scope :errors, -> { where(error: true) }

    def full_action
      "#{controller}##{action}"
    end

  end
end

app/models/speedup_dashboard/server.rb
module SpeedupDashboard
  class Server < ActiveRecord::Base

    before_create :set_defaults

    has_many :requests

    def self.current=(server)
      Thread.current[:server] = server
    end

    def self.current
      Thread.current[:server]
    end

    private

      def set_defaults
        self.api_key = SecureRandom.hex
      end

  end
end

app/controllers/speedup_dashboard/application_controller.rb
module SpeedupDashboard
  class ApplicationController < ActionController::Base

    def render_error(status, message=nil)
      @message = message
      render 'speedup_dashboard/common/error', status: status
      false
    end

    def render_403
      render_error(403)
    end

    def authorize_server
      unless set_server
        return render_403
      end
    end

    def find_optional_server
      @server = Server.find_by(id: params[:server_id])
    end

    private

      def set_server
        key = api_key_from_request
        return false unless key
        Server.current = Server.find_by(api_key: key)
      end

      # Returns the API key present in the request
      def api_key_from_request
        if params[:key].present?
          params[:key].to_s
        elsif request.headers["X-SUR-API-Key"].present?
          request.headers["X-SUR-API-Key"].to_s
        end
      end

  end
end

app/controllers/speedup_dashboard/requests_controller.rb
require_dependency "speedup_dashboard/application_controller"

require_dependency "speedup-dashboard/request_store"

module SpeedupDashboard
  class RequestsController < ApplicationController

    before_action :authorize_server, only: [:create]
    before_action :find_optional_server, only: [:index]
    before_action :prepare_contexts

    layout 'speedup_dashboard/server'

    def index
      scope = (@server && @server.requests)
      scope ||= Request.all

      @from = Time.now - 5.days
      @to = Time.now
      @requests = scope.between(@from, @to)
      if params[:c] && params[:a]
        @action = "#{params[:c]}##{params[:a]}"
        @requests = @requests.where(controller: params[:c], action: params[:a])
      end

      if @context = params[:context]
        @context_data = Context.where(name: @context, request_id: @requests)
      else
        @errors_count = @requests.errors.count
        @error_rate = @requests.count > 0 ? ((@errors_count.to_f / @requests.count) * 10000).round.to_f / 100 : 0
      end

      render "speedup_dashboard/contexts/#{@context}" if @context
    end

    def show
      @request = Request.find(params[:id])
    end

    def create
      @request = SpeedupDashboard::RequestStore.new(params[:request_id])
      @request.load(params[:contexts], params[:data])
      @request.save

      respond_to do |format|
        format.json { render nothing: true}
      end
    end

    private
      def prepare_contexts
        @contexts = Context.uniq.pluck(:name)
      end


  end
end

app/controllers/speedup_dashboard/servers_controller.rb
require_dependency "speedup_dashboard/application_controller"

module SpeedupDashboard
  class ServersController < ApplicationController

    def index
      @servers = Server.all
      @server = Server.new
    end

    def new
      @server = Server.new
    end

    def create
      @server = Server.new(server_params)
      if @server.save
        flash[:notice] = t(:notice_server_created)
        redirect_to action: :index
      else
        render :new
      end
    end

    private

      def server_params
        params.require(:server).permit(:name, :host)
      end

  end
end

app/helpers/speedup_dashboard/application_helper.rb
module SpeedupDashboard
  module ApplicationHelper

    def format_ms(value)
      return '-' unless value
      ((value * 100).round.to_f / 100).to_s + ' ms'
    end
  end
end

app/helpers/speedup_dashboard/requests_helper.rb
module SpeedupDashboard
  module RequestsHelper
  end
end

app/helpers/speedup_dashboard/servers_helper.rb
module SpeedupDashboard
  module ServersHelper
  end
end

app/views/layouts/speedup_dashboard/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/speedup_dashboard/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Performance Dashboard', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to t(:servers), servers_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/speedup_dashboard/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : 'Performance Dashboard' %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Performance Dashboard' %>">
    <%= stylesheet_link_tag 'speedup_dashboard/application', media: 'all' %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag 'speedup_dashboard/application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/speedup_dashboard/navigation' %>
    </header>
    <main class="container-fluid" role="main">
       <%= render 'layouts/speedup_dashboard/messages' %>
       <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/layouts/speedup_dashboard/server.html.erb
<% content_for :content do %>
  <div class="row">
    <div class="col-xs-2 sidebar">
      <% if @server && !@server.new_record? %>
        <h2><%= @server.name %></h2>
        <%#= link_to('Actions', server_actions_path(@server)) %>
      <% end %>
      <ul class="nav nav-sidebar">
        <li><%= link_to('Requests', params.merge(context: nil) ) %></li>
        <% @contexts.each do |context| %>
          <li><%= link_to(context.to_s.humanize, params.merge(context: context) ) %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-xs-10 col-xs-offset-2">
      <h2><%= @action || 'Preview' %><%= " > #{@context}" if @context %></h2>
      <%= yield %>
    </div>
  </div>
<% end %>
<%= render template: 'layouts/speedup_dashboard/application' %>

app/views/speedup_dashboard/common/_queries_list.html.erb
  <strong>queries:</strong> <%= queries.count %> (<%= format_ms queries.sum(:duration) %>)
  <table id="queries" class="table">
    <% queries.each do |query| %>
      <tr>
        <td><%= format_ms query.duration %></td>
        <td><%= query.data['query'] %></td>
      </tr>
    <% end %>
  </table>

app/views/speedup_dashboard/common/error.json.erb
{error: '<%= @message %>'}

app/views/speedup_dashboard/contexts/queries.html.erb
<strong>Average query count: </strong>
<%= @context_data.average_info_count %>

<%= area_chart @context_data.joins(:request).group_by_minute("#{SpeedupDashboard::Request.table_name}.time").average(:context_infos_count) %>


<h3>Sample request</h3>
<%= render 'speedup_dashboard/common/queries_list', queries: @context_data.last.context_infos %>

app/views/speedup_dashboard/requests/index.html.erb
<table class="table">
  <tbody>
    <tr>
      <td><%= @error_rate %>%</td>
      <td><%= format_ms @requests.average(:duration) %></td>
    </tr>
  </tbody>
  <thead>
    <tr>
      <th>Error rate</th>
      <th>Avg request time</th>
    </tr>
  </thead>
</table>

<h3>Performance</h3>
<%= area_chart @requests.group_by_minute(:created_at).average(:duration), {library: {vAxis: {title: "ms"}}} %>

<% if @action && (request = @requests.last) %>
  <% queries = request.context_infos.where(speedup_dashboard_contexts: {name: 'queries'}) %>
  <h3>Sample request</h3>
  <strong>id:</strong> <%= request.id %>
  <strong>duration:</strong> <%= request.duration %>

  <%= render 'speedup_dashboard/common/queries_list', queries: queries %>

<% else %>
  <h3>Most time consuming</h3>
  <table class="table">
    <tbody>
      <% @requests.group(:controller, :action).order(SpeedupDashboard::Request.arel_table[:duration].average.to_sql+' DESC').limit(5).average(:duration).each do |request, value| %>
        <tr>
          <td>
            <%= link_to(params.merge(c: request.first, a: request.second)) do %>
              <%= request.first %>#<%= request.second %>
            <% end %>
          </td>
          <td><%= format_ms(value) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/speedup_dashboard/requests/show.html.erb
<h1><%= @request.controller %>#<%= @request.action %></h1>

app/views/speedup_dashboard/servers/_form.html.erb
<%= bootstrap_form_for(server) do |f| %>
  <%= f.text_field(:name) %>
  <%= f.text_field(:host) %>
  <%= f.submit %>
<% end %>

app/views/speedup_dashboard/servers/index.html.erb
<h3>Registered servers</h3>
<table class="table">
  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= server.host %></td>
        <td><%= server.api_key %></td>
        <td><%= link_to( 'Report', server_requests_path(server) ) %></td>
      </tr>
    <% end %>
  </tbody>
  <thead>
    <tr>
      <th>Name</th>
      <th>Host</th>
      <th>API key</th>
      <th></th>
    </tr>
  </thead>
</table>

<h3>New server</h3>
<%= render 'form', server: @server %>

app/views/speedup_dashboard/servers/new.html.erb
<%= render 'form', server: @server %>